routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'guest:admin', 'namespace' => 'admin', 'as' => ''], function () {
    Route::any('login', 'LoginController@index')->name('login');
    Route::post('checklogin', 'LoginController@checklogin')->name('admin.checklogin');
});
Route::group(['middleware' => 'auth:admin', 'namespace' => 'admin', 'as' => 'admin.'], function () {
    Route::get('', 'HomeController@index')->name('dashboard');
    Route::get('logout', 'LoginController@logout')->name('logout');

    Route::get('settings', 'SettingController@index')->name('setting');
    Route::post('settings', 'SettingController@store')->name('setting.update');
    
    // User
    Route::get('user/delete/{user:id}', 'UserController@delete')->name('user.delete');
    Route::get('user/documentstatus/{user:id}', 'UserController@documentstatus')->name('user.documentstatus');
    Route::get('user/status/{user:id}', 'UserController@status')->name('user.status');
    Route::get('user/csv', 'UserController@csv')->name('user.csv');
    Route::get('user/pdf', 'UserController@pdf')->name('user.pdf');

    // Product
    Route::get('product/delete/{product:id}', 'ProductController@delete')->name('product.delete');
    Route::get('product/status/{product:id}', 'ProductController@status')->name('product.status');
    
    // Kit
    Route::get('kit/delete/{kit:id}', 'KitController@delete')->name('kit.delete');
    Route::get('kit/status/{kit:id}', 'KitController@status')->name('kit.status');
    Route::post('get_products_price', 'KitController@get_products_price')->name('get_products_price');

    // Faqs
    Route::get('faqs/delete/{faq:id}', 'FaqController@delete')->name('faqs.delete');

    // Faqs
    Route::get('page/delete/{page:id}', 'PageController@delete')->name('page.delete');

    // Blog Category
    Route::get('blogcategory/delete/{blogcategory:id}', 'BlogCategoryController@delete')->name('blogcategory.delete');
    
    // Blog
    Route::get('blog/delete/{blog:id}', 'BlogController@delete')->name('blog.delete');
    Route::get('blog/status/{blog:id}', 'BlogController@status')->name('blog.status');
    Route::get('blog/csv', 'BlogController@csv')->name('blog.csv');
    Route::get('blog/pdf', 'BlogController@pdf')->name('blog.pdf');

    Route::resources([
        'user' => UserController::class,
        'product' => ProductController::class,
        'kit' => KitController::class,
        'faqs' => FaqController::class,
        'page' => PageController::class,
        'blog' => BlogController::class,
        'blogcategory' => BlogCategoryController::class,
    ]);
    
    Route::get('order/delete/{order:id}', 'OrderController@delete')->name('order.delete');
    Route::get('order/show/{order:id}', 'OrderController@show')->name('order.show');
    Route::get('order/status/{order:id}', 'OrderController@status')->name('order.status');

    Route::get('order', 'OrderController@index')->name('order');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::any('admin', function () {
    return false;
});

Route::group(['middleware' => 'guest', 'as' => ''], function () {
    Route::get('register/{kit:slug}', 'RegisterController@index')->name('auth.register');
    Route::post('register/{kit:slug}', 'RegisterController@store')->name('auth.register.store');
    Route::get('register/kyc/{id}/{kit:slug}', 'RegisterController@kyc')->name('auth.kyc');
    Route::post('register/kyc/{id}/{kit:slug}', 'RegisterController@register')->name('auth.kyc.store');
    Route::get('login', 'LoginController@index')->name('auth.login');
    Route::post('checklogin', 'LoginController@checklogin')->name('auth.checklogin');

    Route::get('forgot', 'RegisterController@forgot')->name('auth.forgot');

    Route::group(['middleware' => 'guest', 'prefix' => 'ajex', 'as' => 'ajex.'], function () {
        Route::post('register/check', 'AjexController@check')->name('check');
    });

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('package', 'HomeController@kit')->name('kit');
    Route::get('package/{kit:slug}', 'HomeController@kitdetail')->name('kit.detail');
    Route::get('product', 'HomeController@product')->name('product');
    Route::get('product/{product:slug}', 'HomeController@productdetail')->name('product.detail');
    Route::get('blog', 'HomeController@blog')->name('blog');
    Route::get('blog/{blog:slug}', 'HomeController@blogdetail')->name('blog.detail');
    Route::get('termcondition', 'HomeController@termcondition')->name('termcondition');
});
Route::group(['middleware' => 'auth:user', 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('', 'UserController@index')->name('dashboard');
    Route::get('product', 'UserController@product')->name('product');
    Route::get('product/{product:slug}', 'UserController@productdetail')->name('product.detail');
    Route::get('profile', 'UserController@profile')->name('profile');
    Route::post('editprofile', 'UserController@editprofile')->name('editprofile');
    Route::post('changepassword', 'UserController@changepassword')->name('changepassword');
    Route::get('logout', 'LoginController@logout')->name('logout');

    Route::get('checkout/{kit:slug}', 'CheckoutController@index')->name('checkout');
    Route::post('checkout', 'CheckoutController@store')->name('checkout.store');

    Route::post('address/store', 'AddressController@store')->name('address.store');

    Route::get('members', 'UserController@members')->name('members');
    Route::get('order', 'OrderController@index')->name('order');
    Route::get('order/{order:id}', 'OrderController@show')->name('order.invoice');
    Route::post('checkout', 'CheckoutController@store')->name('checkout.store');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    // protected $fillable = [
    //     'name',
    //     'email',
    //     'password',
    // ];
    protected $guarded = [];
    protected $with = ['referal_user'];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role()
    {
        return $this->hasOne('App\Models\Role', 'id', 'role_id');
    }

    public function referal_user()
    {
        return $this->hasOne(User::class, 'id', 'referal_id');
    }

    public function members()
    {
        return $this->hasMany(User::class, 'referal_id', 'id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Order;
use App\Models\Product;
use App\Models\User;
use App\Models\Wallet;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class UserController extends BaseController
{
    public function index()
    {
        $user = Auth::guard('user')->user();
        $chart_user = User::where('referal_id', $user->id)->select(\DB::raw('count(id) as `data`'), \DB::raw('YEAR(created_at) year, MONTH(created_at) month'))
            ->groupby('year', 'month')
            ->get();
        $chart_users = [];
        foreach ($chart_user as $key => $u) {
            $chart_users[] = $u->data;
        }
        $chart_users = implode(',', $chart_users);
        $chart_income = [];
        $chart_income = implode(',', $chart_income);
        $members = User::where('referal_id', $user->id)->get();
        $wallet = Wallet::where('user_id', $user->id)->first();
        $orders = Order::where('user_id', $user->id)->get();
        $data = compact('members', 'wallet', 'orders', 'chart_users', 'user', 'chart_income');
        // dd($data);
        return view('frontend.inc.user.dashboard', $data);
    }

    public function profile(Request $request)
    {
        $user = Auth::guard('user')->user();
        $user = User::find($user->id);

        $request->replace($user->toArray());
        $request->flash();

        $data = compact('user');
        return view('frontend.inc.user.profile', $data);
    }
    public function editprofile(Request $request)
    {
        $user = Auth::guard('user')->user();
        $rules = [
            "name"      => "required",
            "aadhar_number" => "required|numeric|digits:12",
            "pan_number"     => "required|size:10",
        ];
        $request->validate($rules);

        $input = $request->except('_token', 'aadhar_front', 'aadhar_back', 'pan_image', 'password');
        $user->fill($input);
        $user->save();

        if ($request->hasFile('image')) {
            $file  = $request->file('image');
            $name  = 'IMG_' . $user->id . '.' . $file->getClientOriginalExtension();

            $image = Image::make($file)->resize(200, 200, function ($constraint) {
                $constraint->aspectRatio();
            });
            Storage::put('public/user/' . $name, (string) $image->encode());
            $user->update(['image' => $name]);
        }
        if ($request->hasFile('aadhar_front')) {
            $file  = $request->file('aadhar_front');
            $name  = 'IMG_front' . $user->id . '.' . $file->getClientOriginalExtension();

            $image = Image::make($file)->resize(300, 200, function ($constraint) {
                $constraint->aspectRatio();
            });
            Storage::put('public/aadharcard/' . $name, (string) $image->encode());
            $user->update(['aadhar_front' => $name]);
        }
        if ($request->hasFile('aadhar_back')) {
            $file  = $request->file('aadhar_back');
            $name  = 'IMG_back' . $user->id . '.' . $file->getClientOriginalExtension();

            $image = Image::make($file)->resize(300, 200, function ($constraint) {
                $constraint->aspectRatio();
            });
            Storage::put('public/aadharcard/' . $name, (string) $image->encode());
            $user->update(['aadhar_back' => $name]);
        }
        if ($request->hasFile('pan_image')) {
            $file  = $request->file('pan_image');
            $name  = 'IMG' . $user->id . '.' . $file->getClientOriginalExtension();

            $image = Image::make($file)->resize(300, 200, function ($constraint) {
                $constraint->aspectRatio();
            });
            Storage::put('public/pancard/' . $name, (string) $image->encode());
            $user->update(['pan_image' => $name]);
        }

        return redirect()->back()->with('success', 'Profile updated successfully.');
    }
    public function changepassword(Request $request)
    {
        $rules = [
            'oldpassword' => 'required',
            'newpassword' => 'required|string|min:6',
            'confirmpassword' => 'required|same:newpassword|min:6'
        ];

        $request->validate($rules);
        $user = Auth::guard('user')->user();
        if (!Hash::check($user->password, Hash::make($request->oldpassword))) {
            User::where('id', $user->id)->update(['password' => Hash::make($request->newpassword)]);
            return redirect()->back()->with('success', 'Your password has been changed!');
        } else {
            return redirect()->back()->with('error', 'Current password has been not correct.');
        }
    }
    public function product(Request $request)
    {
        $query = Product::where('status', true);
        if ($request->s) {
            $query->where('name', 'LIKE', '%' . $request->s . '%');
        }
        $lists = $query->get();
        $data = compact('lists');
        return view('frontend.inc.user.product', $data);
    }
    public function productdetail(Product $product)
    {
        $data = compact('product');
        return view('frontend.inc.user.productdetail', $data);
    }
    public function members(Request $request)
    {
        $user = Auth::guard('user')->user();
        $members = User::where('referal_id', $user->id)->get();
        $data = compact('members', 'user');
        return view('frontend.inc.user.members', $data);
    }
}

resources/views/backend/inc/user/list.blade.php
@section('style')

@stop
<div class="main-content app-content mt-0">
    <div class="side-app">
        <!-- CONTAINER -->
        <div class="main-container container-fluid">
            <!-- PAGE-HEADER -->
            <div class="page-header">
                <h1 class="page-title">User List</h1>
                <div>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">User</li>
                    </ol>
                </div>
            </div> <!-- PAGE-HEADER END -->
            <!-- Row -->
            <div class="row row-sm">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">User List</h3>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                @if($message = Session::get('error'))
                                <div class="alert alert-danger alert-block">
                                    {{$message}}
                                </div>
                                @endif
                                @if($message = Session::get('success'))
                                <div class="alert alert-success alert-block">
                                    {{$message}}
                                </div>
                                @endif
                                <form class="needs-validation">
                                    <div class="d-flex">
                                        <div style="display: flex; align-items: center; margin-right: 10px; min-width: 100px;">
                                            <label for="limit" style="margin-right: 5px;">Limit</label>
                                            <select name="limit" class="form-control select2" id="limit" style="margin-right: 10px; min-width: 60px;">
                                                <option value="10" @if(@$query['limit']==10) selected @endif>10</option>
                                                <option value="50" @if(@$query['limit']==50) selected @endif>50</option>
                                                <option value="100" @if(@$query['limit']==100) selected @endif>100</option>
                                            </select>
                                        </div>
                                        <div style="margin-right: 10px;">
                                            <input type="text" name="s" value="{{ @$query['s'] }}" class="form-control" placeholder="Search..." style="min-width: 100px;" />
                                        </div>
                                        <div style="margin-right: 10px;">
                                            <select name="user" class="form-control select2" style="margin-right: 20px; min-width: 100px;">
                                                <option value=""> Select User </option>
                                                @foreach($users as $cat)
                                                <option value="{{ $cat->id }}" @if(@$query['user']==$cat->id) selected @endif>{{ $cat->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <div style="margin-right: 10px;">
                                            <select name="status" class="form-control select2" style="margin-right: 20px; min-width: 100px;">
                                                <option value="">Select Status</option>
                                                <option value="true" @if(@$query['status']=='true' ) selected @endif>True</option>
                                                <option value="false" @if(@$query['status']=='false' ) selected @endif>False</option>
                                            </select>
                                        </div>
                                        <div style="margin-right: 10px;"><Button class="btn btn-primary">Submit</Button></div>
                                        <div style="margin-right: 10px;"><a href="{{ route('admin.user.index') }}" class="btn btn-danger" style="background-color: #e74c3c;">Clear All</a></div>
                                        <div style="margin-right: 10px;"><a href="{{ route('admin.user.csv',@$query) }}" class="btn btn-danger" style="background-color: #e74c3c;">Export CSV</a></div>
                                        <div style="margin-right: 10px;"><a href="{{ route('admin.user.pdf',@$query) }}" target="_blank" class="btn btn-danger" style="background-color: #e74c3c;">Export PDF</a></div>
                                    </div>
                                </form>
                                <table class="table border text-nowrap text-md-nowrap table-bordered mb-0 mt-5">
                                    <thead>
                                        <tr>
                                            <th>S. No.</th>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Mobile</th>
                                            <th>Aadhar card</th>
                                            <th>Pancard</th>
                                            <th>Referal By</th>
                                            <th>Lavel</th>
                                            <th>Code</th>
                                            <th>Created at</th>
                                            <th>Document Status</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @php
                                        $sn = $lists->firstItem();
                                        @endphp
                                        @foreach($lists as $key => $list)
                                        <tr>
                                            <td>{{ $sn + $key }}.</td>
                                            <td>
                                                <div class="d-flex">
                                                    <span class="avatar bradius" style="background-image: url('{{ url('storage/user',$list->image)}}');"></span>
                                                    <div class="ms-3 mt-0 mt-sm-2 d-block">
                                                        <h6 class="mb-0 fs-14 fw-semibold"> {{ $list->name }}</h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td><a href="mailto:{{ $list->email }}">{{ $list->email }}</a></td>
                                            <td><a href="tel:{{ $list->mobile }}">{{ $list->mobile }}</a></td>
                                            <td>
                                                <div class="d-flex">
                                                    <span class="avatar bradius" style="background-image: url('{{ url('storage/aadharcard',$list->aadhar_front)}}');"></span>
                                                    <span class="avatar bradius" style="background-image: url('{{ url('storage/aadharcard',$list->aadhar_back)}}');"></span>
                                                    <div class="ms-3 mt-0 mt-sm-2 d-block">
                                                        <h6 class="mb-0 fs-14 fw-semibold"> {{ $list->aadhar_number }}</h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="d-flex">
                                                    <span class="avatar bradius" style="background-image: url('{{ url('storage/pancard',$list->pan_image)}}');"></span>
                                                    <div class="ms-3 mt-0 mt-sm-2 d-block">
                                                        <h6 class="mb-0 fs-14 fw-semibold"> {{ $list->pan_number }}</h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>{{ $list->referal_id ? $list->referal_user->name : 'N/A' }}</td>
                                            <td>Lavel {{ $list->lavel }}</td>
                                            <td>{{ $list->referal_code }}</td>
                                            <td>{{ $list->created_at }}</td>
                                            <td>
                                                <div class="mt-sm-1 d-block">
                                                    @if($list->is_document == 'completed')
                                                    <a href="#" data-url="{{ route('admin.user.documentstatus',$list->id) }}" id="single_status">
                                                        <span class="badge bg-success-transparent rounded-pill text-success p-2 px-3">Completed</span>
                                                    </a>
                                                    @else
                                                    <a href="#" data-url="{{ route('admin.user.documentstatus',$list->id) }}" id="single_status">
                                                        <span class="badge bg-warning-transparent rounded-pill text-warning p-2 px-3">Pending</span>
                                                    </a>
                                                    @endif
                                                </div>
                                            </td>
                                            <td>
                                                <div class="mt-sm-1 d-block">
                                                    @if($list->status == 'true')
                                                    <a href="#" data-url="{{ route('admin.user.status',$list->id) }}" id="single_status">
                                                        <span class="badge bg-success-transparent rounded-pill text-success p-2 px-3">True</span>
                                                    </a>
                                                    @else
                                                    <a href="#" data-url="{{ route('admin.user.status',$list->id) }}" id="single_status">
                                                        <span class="badge bg-danger-transparent rounded-pill text-warning p-2 px-3">False</span>
                                                    </a>
                                                    @endif
                                                </div>
                                            </td>
                                            <td>
                                                <div class="btn-list">

                                                    <a href="{{ route('admin.user.edit',$list->id) }}" class="btn btn-sm btn-primary">
                                                        <span class="fe fe-edit"> </span>
                                                    </a>
                                                    <a href="#" data-url="{{ route('admin.user.delete',$list->id) }}" id="single_delete" class="btn btn-sm btn-danger">
                                                        <span class="fe fe-trash-2"> </span>
                                                    </a>
                                                    <a href="{{ route('admin.user.show',$list->id) }}" class="btn btn-sm btn-warning">
                                                        <span class="fe fe-eye"> </span>
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <div class="mt-3">
                                @if(method_exists($lists, 'links'))
                                @include('frontend.templete.pagination', ['paginator' => $lists,'query'=>$query,'link_limit'=>5])
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- End Row -->
        </div> <!-- CONTAINER CLOSED -->
    </div>
</div>
@section('script')


@stop