routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'guest:admin', 'namespace' => 'admin', 'as' => ''], function () {
    Route::any('login', 'LoginController@index')->name('login');
    Route::post('checklogin', 'LoginController@checklogin')->name('admin.checklogin');
});
Route::group(['middleware' => 'auth:admin', 'namespace' => 'admin', 'as' => 'admin.'], function () {
    Route::get('', 'HomeController@index')->name('dashboard');
    Route::get('logout', 'LoginController@logout')->name('logout');

    Route::get('settings', 'SettingController@index')->name('setting');
    Route::post('settings', 'SettingController@store')->name('setting.update');
    
    // User
    Route::get('user/delete/{user:id}', 'UserController@delete')->name('user.delete');
    Route::get('user/documentstatus/{user:id}', 'UserController@documentstatus')->name('user.documentstatus');
    Route::get('user/status/{user:id}', 'UserController@status')->name('user.status');
    Route::get('user/csv', 'UserController@csv')->name('user.csv');
    Route::get('user/pdf', 'UserController@pdf')->name('user.pdf');

    // Product
    Route::get('product/delete/{product:id}', 'ProductController@delete')->name('product.delete');
    Route::get('product/status/{product:id}', 'ProductController@status')->name('product.status');
    
    // Kit
    Route::get('kit/delete/{kit:id}', 'KitController@delete')->name('kit.delete');
    Route::get('kit/status/{kit:id}', 'KitController@status')->name('kit.status');
    Route::post('get_products_price', 'KitController@get_products_price')->name('get_products_price');

    // Faqs
    Route::get('faqs/delete/{faq:id}', 'FaqController@delete')->name('faqs.delete');

    // Faqs
    Route::get('page/delete/{page:id}', 'PageController@delete')->name('page.delete');

    // Blog Category
    Route::get('blogcategory/delete/{blogcategory:id}', 'BlogCategoryController@delete')->name('blogcategory.delete');
    
    // Blog
    Route::get('blog/delete/{blog:id}', 'BlogController@delete')->name('blog.delete');
    Route::get('blog/status/{blog:id}', 'BlogController@status')->name('blog.status');
    Route::get('blog/csv', 'BlogController@csv')->name('blog.csv');
    Route::get('blog/pdf', 'BlogController@pdf')->name('blog.pdf');

    Route::resources([
        'user' => UserController::class,
        'product' => ProductController::class,
        'kit' => KitController::class,
        'faqs' => FaqController::class,
        'page' => PageController::class,
        'blog' => BlogController::class,
        'blogcategory' => BlogCategoryController::class,
    ]);
    
    Route::get('order/delete/{order:id}', 'OrderController@delete')->name('order.delete');
    Route::get('order/show/{order:id}', 'OrderController@show')->name('order.show');
    Route::get('order/status/{order:id}', 'OrderController@status')->name('order.status');

    Route::get('order', 'OrderController@index')->name('order');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::any('admin', function () {
    return false;
});

Route::group(['middleware' => 'guest', 'as' => ''], function () {
    Route::get('register/{kit:slug}', 'RegisterController@index')->name('auth.register');
    Route::post('register/{kit:slug}', 'RegisterController@store')->name('auth.register.store');
    Route::get('register/kyc/{id}/{kit:slug}', 'RegisterController@kyc')->name('auth.kyc');
    Route::post('register/kyc/{id}/{kit:slug}', 'RegisterController@register')->name('auth.kyc.store');
    Route::get('login', 'LoginController@index')->name('auth.login');
    Route::post('checklogin', 'LoginController@checklogin')->name('auth.checklogin');

    Route::get('forgot', 'RegisterController@forgot')->name('auth.forgot');

    Route::group(['middleware' => 'guest', 'prefix' => 'ajex', 'as' => 'ajex.'], function () {
        Route::post('register/check', 'AjexController@check')->name('check');
    });

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('package', 'HomeController@kit')->name('kit');
    Route::get('package/{kit:slug}', 'HomeController@kitdetail')->name('kit.detail');
    Route::get('product', 'HomeController@product')->name('product');
    Route::get('product/{product:slug}', 'HomeController@productdetail')->name('product.detail');
    Route::get('blog', 'HomeController@blog')->name('blog');
    Route::get('blog/{blog:slug}', 'HomeController@blogdetail')->name('blog.detail');
    Route::get('termcondition', 'HomeController@termcondition')->name('termcondition');
});
Route::group(['middleware' => 'auth:user', 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('', 'UserController@index')->name('dashboard');
    Route::get('product', 'UserController@product')->name('product');
    Route::get('product/{product:slug}', 'UserController@productdetail')->name('product.detail');
    Route::get('profile', 'UserController@profile')->name('profile');
    Route::post('editprofile', 'UserController@editprofile')->name('editprofile');
    Route::post('changepassword', 'UserController@changepassword')->name('changepassword');
    Route::get('logout', 'LoginController@logout')->name('logout');

    Route::get('checkout/{kit:slug}', 'CheckoutController@index')->name('checkout');
    Route::post('checkout', 'CheckoutController@store')->name('checkout.store');

    Route::post('address/store', 'AddressController@store')->name('address.store');

    Route::get('members', 'UserController@members')->name('members');
    Route::get('order', 'OrderController@index')->name('order');
    Route::get('order/{order:id}', 'OrderController@show')->name('order.invoice');
    Route::post('checkout', 'CheckoutController@store')->name('checkout.store');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $guarded = [];
    protected $with = ['images'];

    public function images()
    {
        return $this->hasMany(ProductImage::class, 'product_id', 'id');
    }
}

app/Http/Controllers/admin/ProductController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $page = 'product.list';
        $title = 'Product';

        $lists = Product::withCount('images')->get();

        $data = compact('page', 'title', 'lists');
        return view('backend.layout', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page = 'product.add';
        $title = 'Product Add';

        $data = compact('page', 'title');
        return view('backend.layout', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            "name"      => "required",
            "slug"      => "unique:products",
            "price"     => "required|numeric",
        ];
        $request->validate($rules);

        $input = $request->except('_token', 'image');
        $product = new Product;
        $input['slug']    = $input['slug'] == '' ? Str::slug($input['name'], '-') : $input['slug'];
        $product->fill($input);
        $product->save();

        if ($request->hasFile('image')) {
            $file  = $request->file('image');
            $uniq_id = uniqid();
            $name  = 'IMG_' . '_' . $product->id . '_' . $uniq_id . '.' . $file->getClientOriginalExtension();

            $image = Image::make($file)->resize(300, 200, function ($constraint) {
                $constraint->aspectRatio();
            });
            Storage::put('public/product/' . $name, (string) $image->encode());
            $product_image = new ProductImage();
            $product_image->product_id = $product->id;
            $product_image->image = $name;
            $product_image->save();
        }

        return redirect(route('admin.product.index'))->with('success', 'New record added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        $page = 'product.view';
        $title = 'View Product';

        $data = compact('page', 'title', 'product');
        return view('backend.layout', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, Product $product)
    {
        $request->replace($product->toArray());
        $request->flash();

        $page = 'product.edit';
        $title = 'Edit Product';

        $data = compact('page', 'title', 'product');
        return view('backend.layout', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $rules = [
            "name"      => "required",
            "slug"      => "required|unique:products,slug," . $product->id,
            "price"     => "required|numeric",
        ];
        $request->validate($rules);

        $input = $request->except('_method', '_token', 'image');
        $product->fill($input);
        $product->save();

        if ($request->hasFile('image')) {
            $file  = $request->file('image');
            $uniq_id = uniqid();
            $name  = 'IMG_' . '_' . $product->id . '_' . $uniq_id . '.' . $file->getClientOriginalExtension();

            $image = Image::make($file)->resize(300, 200, function ($constraint) {
                $constraint->aspectRatio();
            });
            Storage::put('public/product/' . $name, (string) $image->encode());
            $product_image = new ProductImage();
            $product_image->product_id = $product->id;
            $product_image->image = $name;
            $product_image->save();
        }

        return redirect(route('admin.product.index'))->with('success', 'Record updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();

        return redirect(route('admin.product.index'))->with('success', 'Record deleted successfully.');
    }

    public function delete(Product $product)
    {
        $product->images()->delete();
        $product->delete();

        return redirect(route('admin.product.index'))->with('success', 'Record deleted successfully.');
    }
    public function status(Product $product)
    {
        if ($product->status == 'true') {
            $product->status = 'false';
        } else{
                $product->status = 'true';
        }
        $product->save();

        return redirect(route('admin.product.index'))->with('success', 'Record status changed successfully.');
    }
}

resources/views/backend/inc/product/add.blade.php
@section('style')

@stop
<div class="main-content app-content mt-0">
    <div class="side-app">
        <!-- CONTAINER -->
        <div class="main-container container-fluid">
            <!-- PAGE-HEADER -->
            <div class="page-header">
                <h1 class="page-title">Add Product</h1>
                <div>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.product.index') }}">Product</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Add Product</li>
                    </ol>
                </div>
            </div>
            <!-- PAGE-HEADER END -->
            <!-- ROW OPEN -->
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Add Product</h3>
                        </div>
                        <div class="card-body">
                            {{ Form::open(['url' => route('admin.product.store'), 'method'=>'POST', 'files' => true, 'class' => 'needs-validation','novalidate']) }}
                            {{ csrf_field() }}

                            @if($message = Session::get('error'))
                            <div class="alert alert-danger alert-block">
                                {{$message}}
                            </div>
                            @endif
                            @if($message = Session::get('success'))
                            <div class="alert alert-success alert-block">
                                {{$message}}
                            </div>
                            @endif
                            @if(count($errors->all()))
                            @foreach($errors->all() as $error)
                            <div class="alert alert-danger">
                                {{$error}}
                            </div>
                            @endforeach
                            @endif
                            <div class="form-row">
                                <div class="col-xl-12 mb-3">
                                    {{Form::label('name', 'Name')}}
                                    {{Form::text('name', '', ['class' => 'form-control', 'placeholder'=>'Name','required'=>'required'])}}
                                    <div class="invalid-feedback">Please enter name.</div>
                                </div>
                                <div class="col-xl-4 mb-3">
                                    {{Form::label('slug', 'Slug')}}
                                    {{Form::text('slug', '', ['class' => 'form-control', 'placeholder'=>'Slug'])}}
                                    <div class="invalid-feedback">Please enter slug.</div>
                                </div>
                                <div class="col-xl-4 mb-3">
                                    {{Form::label('price', 'Price')}}
                                    {{Form::number('price', '', ['class' => 'form-control', 'placeholder'=>'Price','required'=>'required'])}}
                                    <div class="invalid-feedback">Please enter price.</div>
                                </div>
                                <div class="col-xl-4 mb-3">
                                    {{Form::label('image', 'Image')}}
                                    {{Form::file('image',['class'=>'form-control','required'=>'required'])}}
                                    <div class="invalid-feedback">Please choose image.</div>
                                </div>

                                <div class="col-xl-12 mb-3">
                                    {{Form::label('excerpt', 'Short Description')}}
                                    {{Form::textarea('excerpt', '', ['class' => 'form-control', 'placeholder'=>'Short Description','rows'=>'3'])}}
                                    <div class="invalid-feedback">Please enter short description.</div>
                                </div>
                                <div class="col-xl-12 mb-3">
                                    {{Form::label('description', 'Description')}}
                                    {{Form::textarea('description', '', ['class' => 'form-control', 'placeholder'=>'Description','rows'=>'6'])}}
                                    <div class="invalid-feedback">Please enter description.</div>
                                </div>
                                <!-- <div class="col-xl-12 mb-3">
                                    {{Form::label('description', 'Upload Images')}}
                                    <input id="demo" type="file" name="files" accept=".jpg, .png, image/jpeg, image/png" multiple="" class="ff_fileupload_hidden">
                                </div> -->
                            </div>
                            <button class="btn btn-primary mt-5" type="submit">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div> <!-- ROW CLOSED -->
        </div> <!-- CONTAINER CLOSED -->
    </div>
</div>

@section('script')

<script src="{{ url('assets/plugins/fancyuploader/jquery.fileupload.js') }}"></script>
<script src="{{ url('assets/plugins/fancyuploader/jquery.iframe-transport.js') }}"></script>
<script src="{{ url('assets/plugins/fancyuploader/jquery.fancy-fileupload.js') }}"></script>
<script src="{{ url('assets/plugins/fancyuploader/fancy-uploader.js') }}"></script>
@stop

resources/views/backend/inc/product/list.blade.php
@section('style')

<!-- Edit Table -->
<!-- <link href="{{ url('assets/plugins/edit-table/edit-table.css') }}" rel="stylesheet"> -->

<link href="../assets/plugins/datatable/css/buttons.bootstrap5.min.css" rel="stylesheet">
<link href="../assets/plugins/datatable/responsive.bootstrap5.css" rel="stylesheet" />

@stop
<div class="main-content app-content mt-0">
    <div class="side-app">
        <!-- CONTAINER -->
        <div class="main-container container-fluid">
            <!-- PAGE-HEADER -->
            <div class="page-header">
                <h1 class="page-title">Product List</h1>
                <div>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Product</li>
                    </ol>
                </div>
            </div>
            <!-- PAGE-HEADER END -->
            <!-- Row -->
            <div class="row row-sm">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Product List</h3>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                @if($message = Session::get('error'))
                                <div class="alert alert-danger alert-block">
                                    {{$message}}
                                </div>
                                @endif
                                @if($message = Session::get('success'))
                                <div class="alert alert-success alert-block">
                                    {{$message}}
                                </div>
                                @endif
                                <div id="responsive-datatable_wrapper" class="dataTables_wrapper dt-bootstrap5 no-footer">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <table class="table table-bordered text-nowrap border-bottom dataTable no-footer" id="responsive-datatable" role="grid" aria-describedby="responsive-datatable_info">
                                                <thead>
                                                    <tr role="row">
                                                        <th class="wd-15p border-bottom-0 sorting sorting_asc" tabindex="0" aria-controls="responsive-datatable" rowspan="1" colspan="1">S. No.</th>
                                                        <th class="wd-15p border-bottom-0 sorting sorting_asc" tabindex="0" aria-controls="responsive-datatable" rowspan="1" colspan="1">Name</th>
                                                        <th class="wd-15p border-bottom-0 sorting sorting_asc" tabindex="0" aria-controls="responsive-datatable" rowspan="1" colspan="1">Price</th>
                                                        <!-- <th class="wd-15p border-bottom-0 sorting sorting_asc" tabindex="0" aria-controls="responsive-datatable" rowspan="1" colspan="1">Sale Price</th> -->
                                                        <th class="wd-15p border-bottom-0 sorting sorting_asc" tabindex="0" aria-controls="responsive-datatable" rowspan="1" colspan="1">Image</th>
                                                        <!-- <th class="wd-15p border-bottom-0 sorting sorting_asc" tabindex="0" aria-controls="responsive-datatable" rowspan="1" colspan="1">Excerpt</th> -->
                                                        <th class="wd-25p border-bottom-0 sorting" tabindex="0" aria-controls="responsive-datatable" rowspan="1" colspan="1">Created at</th>
                                                        <th class="wd-20p border-bottom-0 sorting" tabindex="0" aria-controls="responsive-datatable" rowspan="1" colspan="1">Status</th>
                                                        <th class="wd-25p border-bottom-0" tabindex="0" aria-controls="responsive-datatable" rowspan="1" colspan="1">Action</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach($lists as $key => $list)
                                                    @php
                                                    $sn = $key + 1;
                                                    @endphp
                                                    <tr>
                                                        <td>{{ $sn }}.</td>
                                                        <td>{{ $list->name }}</td>
                                                        <td>₹ {{ $list->price }} /-</td>
                                                        <td>
                                                            <div class="d-flex">
                                                                @if(!$list->images_count)
                                                                N/A
                                                                @else
                                                                @foreach($list->images as $img)
                                                                <span class="avatar bradius" style="background-image: url('{{ url('storage/product',$img->image)}}');"></span>
                                                                @endforeach
                                                                @endif
                                                            </div>
                                                        </td>
                                                        <!-- <td style="max-width: 200px; overflow: hidden; text-overflow: ellipsis;">{{ $list->excerpt ? $list->excerpt : 'N/A' }}</td> -->
                                                        <td>{{ $list->created_at }}</td>
                                                        <td>
                                                            <div class="mt-sm-1 d-block">
                                                                @if($list->status == 'true')
                                                                <a href="#" data-url="{{ route('admin.product.status',$list->id) }}" id="single_status">
                                                                    <span class="badge bg-success-transparent rounded-pill text-success p-2 px-3">True</span>
                                                                </a>
                                                                @else
                                                                <a href="#" data-url="{{ route('admin.product.status',$list->id) }}" id="single_status">
                                                                    <span class="badge bg-warning-transparent rounded-pill text-danger p-2 px-3">False</span>
                                                                </a>
                                                                @endif
                                                            </div>
                                                        </td>
                                                        <td>
                                                            <div class="btn-list">
                                                                <a href="{{ route('admin.product.edit',$list->id) }}" class="btn btn-sm btn-primary">
                                                                    <span class="fe fe-edit"> </span>
                                                                </a>
                                                                <a href="#" data-url="{{ route('admin.product.delete',$list->id) }}" id="single_delete" class="btn btn-sm btn-danger">
                                                                    <span class="fe fe-trash-2"> </span>
                                                                </a>
                                                                <a href="{{ route('admin.product.show',$list->id) }}" class="btn btn-sm btn-warning">
                                                                    <span class="fe fe-eye"> </span>
                                                                </a>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- End Row -->
        </div> <!-- CONTAINER CLOSED -->
    </div>
</div>
@section('script')

<!-- Edit Table -->
<script src="{{ url('assets/plugins/edit-table/edit-table.js') }}"></script>
<script src="{{ url('assets/plugins/edit-table/bst-edittable.js') }}"></script>

<script src="{{ url('assets/plugins/datatable/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ url('assets/plugins/datatable/js/dataTables.bootstrap5.js') }}"></script>
<script src="{{ url('assets/plugins/datatable/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ url('assets/plugins/datatable/js/buttons.bootstrap5.min.js') }}"></script>
<script src="{{ url('assets/plugins/datatable/js/jszip.min.js') }}"></script>
<script src="{{ url('assets/plugins/datatable/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ url('assets/plugins/datatable/pdfmake/vfs_fonts.js') }}"></script>
<script src="{{ url('assets/plugins/datatable/js/buttons.html5.min.js') }}"></script>
<script src="{{ url('assets/plugins/datatable/js/buttons.print.min.js') }}"></script>
<script src="{{ url('assets/plugins/datatable/js/buttons.colVis.min.js') }}"></script>
<script src="{{ url('assets/plugins/datatable/dataTables.responsive.min.js') }}"></script>
<script src="{{ url('assets/plugins/datatable/responsive.bootstrap5.min.js') }}"></script>
<script src="{{ url('assets/js/table-data.js') }}"></script>

@stop